rancilio-pid/clevercoffee

README.md, rancilio-pid/rancilio-pid.ino
=> 1.9.8 master beta

rancilio-pid/Displaytemplateminimal.h
fix #64 by dropping float over 100 degrees
=> no float over 100 degrees

rancilio-pid/userConfig.h
New comment on Displaytemplate 4
=> Displaytemplate 4 commented

rancilio-pid/userConfig.h
Ergänzung der Beschreibung MACHINELOGO = 3 in userConfig.h
=> QuickMill Startlogo

rancilio-pid/Displayrotateupright.h, rancilio-pid/Displaytemplateminimal.h, rancilio-pid/Displaytemplatestandard.h, rancilio-pid/Displaytemplateupright.h, rancilio-pid/display.h, rancilio-pid/languages.h, rancilio-pid/rancilio-pid.ino, rancilio-pid/userConfig.h
This is my effort to have multi-lingual support. I have only bothered with the text that appears in the display. All text that is used for debugging, which was in English already, is not affected by this.
Currently added Spanish and English to German. So far seems to work. But I have only tested with PID only + brewswitch.
=> B multilingual support

rancilio-pid/rancilio-pid/rancilio-pid.ino
Code-Struktur so geändert, dass die Erkennung des Brüh- bzw. Dampfmodus für QuickMill Thermoblock im machinestate 20 erfolgt.
=> QuickMill steam-mode 2.0

rancilio-pid/rancilio-pid/display.h, rancilio-pid/rancilio-pid/rancilio-pid.ino, rancilio-pid/rancilio-pid/userConfig_sample.h
=> typos fixed

platformio.ini, rancilio-pid/rancilio-pid/userConfig_sample.h
Hi,
just a small PR, adding both USB and OTA upload configurations to PlatformIO.
=> USB and OTA configurations in PlatformIO

rancilio-pid/rancilio-pid/brewscaleini.h, rancilio-pid/rancilio-pid/brewvoid.h
Debounced trigger brewswitch and shortened the wait time between brewswitchactivation to 5secs
=> Debounce code

rancilio-pid/rancilio-pid/rancilio-pid.ino
digitalRead PVS only once in brewdetection()
=> debounce 1.0

.editorconfig, rancilio-pid/rancilio-pid/Displaytemplateminimal.h
Apologies for the large number of touched lines. This is a VS Code reformat of this file + simplifying of the conditionals to be more explicit about the number formatting changes.
=> tidy up minimal display template

rancilio-pid/rancilio-pid/rancilio-pid.ino, rancilio-pid/rancilio-pid/userConfig_sample.h
Hi rancilio-pid team!
This is my first PR to this project and therefore quite small. Hopefully the commit comments are meaningful enough.
Best regards,
endym
=> Add offline brew detection limit to userConfig_sample.h & minor code cleanup

rancilio-pid/rancilio-pid/RancilioServer.cpp, rancilio-pid/rancilio-pid/userConfig_sample.h
static content will likely still blow up
=> update sample user config and temporarily disable isr when generating variables

rancilio-pid/libraries/ESPAsyncWebServer/src/WebHandlers.cpp, rancilio-pid/rancilio-pid/RancilioServer.cpp
this is a temporary hack and would need to be replaced with a callback or something else less invasive
=> just testing if we could keep the isr

rancilio-pid/rancilio-pid/RancilioServer.cpp, rancilio-pid/rancilio-pid/RancilioServer.h, rancilio-pid/rancilio-pid/rancilio-pid.ino
=> add eeprom write callback

rancilio-pid/rancilio-pid/RancilioServer.cpp, rancilio-pid/rancilio-pid/RancilioServer.h
See https://github.com/espressif/arduino-esp32/issues/1141
=> Disable timer before SPIFFS access on ESP32

src/Storage.cpp, src/Storage.h
- storageGet() returns a default value now, if no valid value is stored
- storageGet() with a String value will not lead to an unnecessary EEPROM commit anymore
- storageSet() checks data size
- added storageFactoryReset()
=> improved storage module

src/Displayrotateupright.h, src/Displaytemplateminimal.h, src/Displaytemplatescale.h, src/Displaytemplatestandard.h, src/Displaytemplateupright.h, src/ISR.h, src/brewscaleini.h, src/brewvoid.h, src/display.h, src/rancilio-pid.cpp, src/scalevoid.h, src/userConfig_sample.h
Renamed pins to match formt pin+component. translated german variable names and comments
=> Pin renames and comment translation

src/Storage.cpp, src/brewscaleini.h, src/rancilio-pid.cpp, src/userConfig_sample.h
BREW_TIME, BREW_SW_TIMER, PRE_INFUSION_TIME and PRE_INFUSION_PAUSE_TIME
=> added missing system parameter default defines in userConfig

src/RancilioServer.h, src/rancilio-pid.cpp
* Funktion MQTT die von der Webseite aufgerufen wird
* Alle Parameter, die auch in Blynk sind, nach MQTT senden
* Ohne Callback
=> MQTT Funktion

data/html/parameters.htm, src/RancilioServer.h, src/rancilio-pid.cpp
Vars from Blynk to MQTT with writeSysParamsToMQTT();
Vars from MQTT to Blynk with writeSysParamsToBlynk();
one void for mqtt sending, all vars every 5 sec (default)
=> vars from blynk to mqtt and mqtt to blynk via void

data/html/parameters.htm, src/Storage.cpp, src/Storage.h, src/brewscaleini.h, src/rancilio-pid.cpp
* Scale in der Website
* Frage: float to double unproblematisch bei weightSetpoint?
=> Alpha 3.0.0

data/html/parameters.htm, src/Storage.cpp, src/Storage.h, src/rancilio-pid.cpp, src/userConfig_sample.h
* steam kp eeprom
* steam kp mqtt
* steam kp website
* userconfig example blynk, mqtt, grafana 0
=> steamkp mqtt and website

data/html/index.htm, data/html/parameters.htm, data/js/temp.js, src/RancilioServer.h, src/rancilio-pid.cpp
* Dynamically update temperature value on start page
* Render uint8_t values in forms as checkboxes
=> Website fixes

data/js/temp.js
- Bugfix: time format on x axis not y axis
- feature: zoom y axis allowed
=> Alpha 3.0.0/website zooom only

src/rancilio-pid.cpp
FIx timeout for Portal and timeout for wlan connection
=> fix timeout wifi manager

src/rancilio-pid.h
To fix Cold Start Kp being too low for Quick Mill Machines
=> Quick Mill Cold Start Kp

src/Displaytemplatescale.h, src/brewvoid.h
=> Added #if directive in Displaytemplatescale.h to fix compilation error

README.md, data/html_fragments/header.htm, platformio.ini, src/Displaytemplateminimal.h, src/Displaytemplatescale.h, src/Displaytemplatestandard.h, src/Displaytemplatetemponly.h, src/Displaytemplateupright.h, src/RancilioServer.h, src/Storage.cpp, src/Storage.h, src/brewvoid.h, src/display.h, src/languages.h, src/rancilio-pid.cpp, src/rancilio-pid.h, src/userConfig_sample.h
Fixes a few smaller things
* prevent empty favicon requests, supply one inline with the templates (svg with emoji)
* fix logging output when there is a sensor error
* use the ArduinoPID library fork under rancilio-pid
* a few updates to the Readme
=> Various fixes: favicon, logging, use proper PID library

src/rancilio-pid.cpp, src/rancilio-pid.h
Setting steam setpoint via MQTT should now be possible.
It´s my first PR, please be nice to me. :)
See Issue #281
=> Fix MQTT Steam Setpoint

src/rancilio-pid.cpp
* change the will's topic name from will to available
* send offline as last will
* when sending all system parameters also send online for the will topic
=> Use MQTT will for availability

src/RancilioServer.h, src/Storage.cpp, src/Storage.h, src/rancilio-pid.cpp
based off of #294, just added some tweaks to make it work
=> Show steam setpoint on parameters page

src/Displaytemplateminimal.h, src/Displaytemplatescale.h, src/Displaytemplatestandard.h, src/Displaytemplatetemponly.h, src/Displaytemplateupright.h, src/display.h
After removing Blynk, there is empty space between wifi signal bars and MQTT Icon.
Moving MQTT Icon to left where blynk icon was.
=> Move MQTT Icon

platformio.ini
Monitor OTA Port was missing in Platformio.ini
=> Fix missing monitor OTA Port

src/brewscaleini.h, src/brewvoid.h, src/defaults.h, src/main.cpp, src/pinmapping.h, src/userConfig_sample.h
@Invenis: I cherry-picked your commit before making the other changes. Could you close PR #320? Thanks!
=> Fix pin definitions for scale, update pin mapping to match latest revision of the PCB

src/EmbeddedWebserver.h, src/MQTT.h, src/Storage.cpp, src/Storage.h, src/defaults.h, src/main.cpp, src/userConfig_sample.h
also reformat editableVars definition, and clean up some names
=> move brew PID delay parameter to web interface

src/MQTT.h, src/Storage.cpp, src/Storage.h, src/defaults.h, src/main.cpp
Display setup message if wifi manager is in setup mode
=> Display setup message if wifi manager is in setup mode

src/MQTT.h, src/debugSerial.cpp, src/debugSerial.h, src/main.cpp
This isn't tested, as I use neither software BD nor scale. But as the changes are small, I believe there won't be any issues.
EDIT:
I continued to work on this and replaced the mqttVars vector with a map. This is intended to be a precursor to allow Home Assistant MQTT auto discovery.
This time, I have tested the changes and they work without issue for me ;)
=> Replace mqttVars vector with map

src/scalevoid.h
Only bug fixing for Issue #347 , we have to solve it better in the ESP32 master. We use now pre processor commands.
=> bugfix for #347

platformio.ini, src/InfluxDB.h, src/userConfig_sample.h
updated ESP Influxdb LIB to 3.13.1
added option for setInsecure
=> Option to setInsecure for InfluxDB Client

src/InfluxDB.h, src/userConfig_sample.h
added option to define httpReadTimeout
Maybe something for #242
=> Option to define httpReadTimeout

src/InfluxDB.h, src/userConfig_sample.h
* added InfluxDB Check to disable InfluxDB inflight before blocking the ESP
=> Added InfluxDB retries 

src/display.h, src/languages.h
kEmergencyStop was hard coded to german, replaced with langstring_current_temp and langstring_set_temp
=> fix-kEmergencyStop-translation-esp8266

src/main.cpp
Hassio Discovery was sent even if MQTT_HASSIO_SUPPORT was not enabled.
Thanks to @LoQue90 
* added check for Hassio feature
=> [Fix] Hassio Discovery 

src/main.cpp, src/powerswitchvoid.h, src/steamswitchvoid.h, src/userConfig_sample.h
Steam switch has now 3 modes:
off, switch or trigger
removed double pinmode declaration for Steamswitch
renaming powerswitchvoid
=> adding trigger for steammode

src/MQTT.h, src/main.cpp
=> Add machineState to mqtt again

README.md
=> Update README.md - Discord Link

src/userConfig_sample.h
wrong defaults for brewswitchtype
adding comments
=> userconfig fixes

src/display.h, src/languages.h
kEmergencyStop was hard coded to german, replaced with langstring_current_temp and langstring_set_temp
=> fix-kEmergencyStop-translation

src/Displayrotateupright.h, src/userConfig_sample.h
fix missing vars on displaytemplate rotateupright
adding/cleaning comments in userconfig
=> fix display template and clean up

src/userConfig_sample.h
adding/cleaning comments in userconfig
=> cleanup userConfig_sample

src/pinmapping.h
change pinmapping to follow pcb development minimal rev 1.5 and full-feature rev 1.6
=> change pinmapping.h

src/languages.h
translation was only set for template 1-3
=> fix translation DISPLAYTEMPLATE 4

src/languages.h
translation was only set for template 1-3
=> fix translation DISPLAYTEMPLATE 4-esp8266

src/main.cpp
cleanup optocoupler to follow camelcase code style
=> cleanup optocoupler

.github/workflows/main.yml, src/Displayrotateupright.h, src/Displaytemplateminimal.h, src/Displaytemplatescale.h, src/Displaytemplatestandard.h, src/Displaytemplatetemponly.h, src/Displaytemplateupright.h, src/MQTT.h, src/brewvoid.h, src/display.h, src/main.cpp, src/powerswitchvoid.h, src/steamswitchvoid.h, src/userConfig_sample.h
Enable features in userConfig for automatic builds in GitHub Actions.
=> Feature tests

src/languages.h, src/pressure.h, src/userConfig_sample.h
workaround for brewdetection
change wording from display text for backflush
fix pressure sensor serial output to follow verbose config
=> Cleanup from last PRs

platformio.ini, src/Displaytemplateupright.h, src/EmbeddedWebserver.h, src/ISR.cpp, src/PeriodicTrigger.cpp, src/SysPara.h, src/brewvoid.h, src/debugSerial.cpp, src/main.cpp, src/powerswitchvoid.h, src/pressure.h, src/steamswitchvoid.h
* Removed unused code
* Fixed formatting for else statements in accordance with style guidelines
* Bumped versions of espressif framework, u8g2 and OneWire libraries
* Reduce debug output of pressure sensor reading to once per second
=> Code Cleanup, bump version numbers

src/display/displayTemplateTempOnly.h
degree icon didn´t flashed together with shown temp
=> fix non blinking degree icon

src/brewHandler.h, src/display/displayCommon.h, src/main.cpp
ManualFlush does not stop when WaterEmpty triggered.
=> Bugfix: ManualFlush does not stop when WaterEmpty triggered. 

platformio.ini
to fix https://github.com/rancilio-pid/clevercoffee/issues/478
=> update version wifimanager and AsyncTCP

src/display/displayCommon.h, src/display/displayTemplateMinimal.h, src/display/displayTemplateScale.h, src/display/displayTemplateStandard.h, src/display/displayTemplateTempOnly.h, src/display/displayTemplateUpright.h, src/main.cpp, src/userConfig_sample.h
... and `FEATURE_OFFLINELOGO` to `FEATURE_PIDOFF_LOGO`
=> Rename kPidOffline to kPidDisabled

src/brewHandler.h, src/display/displayCommon.h, src/display/displayTemplateUpright.h, src/main.cpp, src/mqtt.h
No functional change, just code cleanup.
=> Compiler warnings / global variable cleanup

src/main.cpp, src/userConfig_sample.h
...tested with my XKC-Y25-PNP.
=> Make Water Sensor an IOSwitch

src/display/displayTemplateMinimal.h
Fixup from earlier cleanup. Precompiler flags get me - every single time...
=> Drop pidMode from displayTemplateMinimal.h

src/main.cpp
Fixed shottimerscale(); never getting called with appropriate settings enabled.
Ps. this is my first pull request. I have about -18 idea what im doing... Hope im helping 😀
=> Fixed the scale readout with timed brewmode selected

platformio.ini
...for @LoQue90 :smile_cat: 
```cpp
#include <variant>
std::variant<double, int> test;
test = 3.14;
if(std::holds_alternative<int>(test)) {
LOG(DEBUG, "Look, an int!");
} else if (std::holds_alternative<double>(test)) {
LOG(DEBUG, "Ooooh, a tiny double!");
}
```
=> Enable Buidling with C++17

platformio.ini
another change in release structure brings build actions to fail
=> bum ESPAsyncWebServer version

platformio.ini, src/embeddedWebserver.h
@LoQue90 I believe these repos are the proper ones to track, compared to #524
=> Update to new AsyncTCP and embedded webserver

platformio.ini
using some more maintained libs, to get more perfomance, less chrashes 
could someone try compatibility with safari?
https://github.com/mathieucarbou/AsyncTCP
https://github.com/mathieucarbou/ESPAsyncWebServer
=> change async libs to more maintained ones

src/display/displayTemplateUpright.h
The vertical template does not support the water sensor or other symbols. This code adds support for the offline, emptywater and heating icon.
Positions for symbols should work, tested on my machine here. The inital if query might be too loose as i added the states here.
=> Enhance vertical template to support some symbols
