- rancilio-pid/Displaytemplateminimal.h
- rancilio-pid/Displaytemplatestandard.h
- rancilio-pid/display.ino
- rancilio-pid/rancilio-pid.ino
- rancilio-pid/userConfig.h
Shottimer zeigt noch für eine bestimmte Zeit nach dem Zurücksetzen des Brühschalters die Shotzeit an.
Hauptsächlich, um bei selbständigem Stoppen des Shots die gebrauchte Zeit noch ablesen zu können.
Zeit ist per Userconfig einstellbar.
> Shottimer update

- rancilio-pid/rancilio-pid.ino
Aktuell wird die SW Brewdetection außerhalb es Temp Fensters ausgelöst. Die kleine Anpassung sollte abhelfen.
> adjust if condition to get correct temp window

- rancilio-pid/rancilio-pid/rancilio-pid.ino
If ´DISPLAY==0´, there is a closing brace without an opening one.
> Not compiling when DISPLAY == 0

- rancilio-pid/rancilio-pid/display.h
#if ONLYPIDSCALE == 1 wurde um einen Block nach unten gesetzt, damit die Bezugszeit am Ende des Brühens (machinestate 31) im Display angezeigt bleibt, wenn ONLYPIDSCALE = 0.
> fix show lastbezugszeit for ONLYPIDSCALE==0

- rancilio-pid/rancilio-pid/Displaytemplateminimal.h
- rancilio-pid/rancilio-pid/Displaytemplatescale.h
- rancilio-pid/rancilio-pid/Displaytemplatestandard.h
- rancilio-pid/rancilio-pid/Displaytemplatetemponly.h
- rancilio-pid/rancilio-pid/Displaytemplateupright.h
- rancilio-pid/rancilio-pid/rancilio-pid.ino
**Abkühlmodus "chill-mode after steam"**
Neuer machinestate 45 für die Abkühlphase nach dem Dampfmodus. In diesem maschinestate kann mit dem Brühschalter ein cooling flush gemacht werden (Shotcounter bleibt aus) oder mit dem Dampfschalter auf steam geschaltet werden.
Wenn bis auf Solltemperatur + 2 °C abgekühlt ist, wird in den idle-Betrieb (machinestate 20) gewechselt.
Für die QuickMill werden im machinestate 45 die PID-Werte auf Dampfeinstellungen belassen, für alle anderen Maschinen wird auf die Brüh-PID-Werte umgeschaltet.
> chill-mode after steam 1.0

- platformio.ini
force platform to version 2.6.3 because 3.x won't compile
> Update platformio.ini to circumvent problem with espressif version 3.x

- rancilio-pid/rancilio-pid/ISR.h
In the current state when the PID controller requests a 100% duty cycle we will disable the heater for one timer interrupt cycle before re-enabling it. This special case allows us to keep the heater on 100% of the time
> Fix 100% duty cycle

- rancilio-pid/rancilio-pid/rancilio-pid.ino
As per description. Alternatively we could turn this function into a void as the result isn't ever used (obviously).
While I was in there I also changed the conditional into a preprocessor directive.
> Return result from non-void function

- rancilio-pid/rancilio-pid/rancilio-pid.ino
without this we *will* run into case `19` after e.g. evaluating the steamOn, pidOn or sensorError conditions -- this has caused trouble on a separate feature I worked on.
> add missing break statement

- rancilio-pid/libraries/Blynk/src/BlynkSimpleEsp8266.h
- rancilio-pid/libraries/ZACwire-Library-1.3.0/ZACwire.h
- rancilio-pid/rancilio-pid/Displayrotateupright.h
- rancilio-pid/rancilio-pid/Displaytemplateminimal.h
- rancilio-pid/rancilio-pid/Displaytemplatescale.h
- rancilio-pid/rancilio-pid/Displaytemplatestandard.h
- rancilio-pid/rancilio-pid/Displaytemplatetemponly.h
- rancilio-pid/rancilio-pid/Displaytemplateupright.h
- rancilio-pid/rancilio-pid/brewvoid.h
- rancilio-pid/rancilio-pid/languages.h
- rancilio-pid/rancilio-pid/rancilio-pid.ino
Fixed a lot of compiler warnings (including a critical buffer overflow).
There are still some warnings left which should be discussed, for example:
- userConfig.h:30:0: warning: "DISPLAY" redefined
- libraries/ZACwire-Library-1.3.0/ZACwire.h:47:68: warning: suggest parentheses around '+' inside '>>' [-Wparentheses]
> fix compiler warnings (incl. buffer overflow)

- rancilio-pid/rancilio-pid/ISR.h
- rancilio-pid/rancilio-pid/rancilio-pid.ino
Dieser Patch behebt die falsche Konfiguration des Timer1 nach einem OTA-Prozess (TIM_DIV16 statt TIM_DIV256).
Zur besseren Handhabung und um zukünftige Inkonsistenzen zu vermeiden, habe ich Funktionen zum Initialisieren, Aus- und Einschalten des Timer1 angelegt. Dadurch wird z. B. auch die Unterscheidung zw. ESP8266 u. ESP32 an zentralen Stellen erledigt. Die Funktionen werden jetzt an den entspr. Code-Stellen verwendet.
> cleaned up timer1 handling (always enable with same settings)

- rancilio-pid/rancilio-pid/rancilio-pid.ino
Diese Patch-Serie beinhaltet folgende Änderungen:
- zentrale Initialisierung des EEPROMs
- EEPROM-Funktionen zum Lesen/Schreiben der Systemparameter-Werte
Die Funktionen vereinheitlichen den Zugriff auf die Systemparameter-Werte im EEPROM. Beim Schreiben wird außerdem der Timer1-Interrupt behandelt. Die Funktionen dienen auch als Vorbereitung für das neue Feature "Display Menu", über das ebenfalls auf das EEPROM zugegriffen werden kann.
Da ich die Blynk-App nicht nutze, konnte ich die Änderungen nur in Verbindung mit dem Display-Menü testen (Lesen/Schreiben der Systemparameter-Werte).
> cleanup EEPROM access

- rancilio-pid/rancilio-pid/rancilio-pid.ino
Verbesserte Erkennung, ob im EEPROM bereits Daten gespeichert wurden oder nicht.
Im Forum wurde berichtet, dass die Heizung beim Erreichen des Temperatur-Sollwerts nicht abschaltet, wenn der Blynk-Server beim Start nicht erreichbar war. In diesem Fall werden die Systemparameter-Werte aus dem EEPROM gelesen. Dabei wurde bisher nur geprüft, ob der erste EEPROM-Wert eine gültige Fließkommazahl ist.
Mit dieser Änderung wird zusätzlich geprüft, ob die ersten 10 Bytes "leer" sind (0xFF) oder nicht.
> improved EEPROM data detection

- rancilio-pid/rancilio-pid/rancilio-pid.ino
- rancilio-pid/rancilio-pid/userConfig_sample.h
Moving the version number from rancilio-pid.ino to userConfig should make it easier to update it. This value gets displayed during startup (and is incorrect in the current release)
> Moved sysversion to config file

- src/rancilio-pid.cpp
- src/rancilio-pid.h
- src/userConfig_sample.h
- comparing strings at preprocessor level is not supported
- userConfig "match check" does not include the branch name (see 1st point)
- use separate defines for all firmware version parts to be more flexible
- added a general function to get the version as string (w/o any other stuff)
this function can be used to build further strings containing the firmware version
- introduced rancilio-pid header file so that other modules may call some functions
> overworked firmware version check

- src/RancilioServer.h
- src/Storage.cpp
- src/SysPara.h
- src/rancilio-pid.cpp
- src/rancilio-pid.h
Die Klasse hat folgende Features:
- Verwaltung von Minimum/Maximum-Werten (zur Prüfung neuer Werte)
- optionales EEPROM-Handling (wenn beim Instanziieren eine Storage-ID angegeben wird): autom. Initialisieren mit EEPROM-Wert, Lesen/Schreiben)
Das kann natürlich dann noch weiter ausgebaut werden. Z. B. könnte man - ähnlich wie das EEPROM-Handling - auch das MQTT-Publish über die Klasse regeln, wenn beim Instanziieren ein MQTT-String angegeben wird.
> Einheitliche Verwaltung von System-Parametern (SysParaClass)

- src/rancilio-pid.cpp
In the current implementation filter an all its gobal values are defined as `int`. So any convergance of the filter value towards the actual pressure value will halt, when the delta is smaller than 1. For example when starting at 0 and having a pressure of 12, the filterd value will converge to 9, because the next increase is below a full integer (9.9). Defining the filter and its globals as `float` will let the pressure value converge as expected.
> Bug fixed where pressure will not converge to actual value.

- src/rancilio-pid.cpp
This also resets the brew detected flag for the OnlyPID+ configuration (optocoupler for brew switch).
Otherwise Brew 0/25 will stay on the screen.
> Show uptime again after a brew with HW brew detection

- src/ISR.h
Compilation failed for ESP32, because "timer" reference to rancilio-pid.cpp had been undefined.
> Fix build for ESP32

- data/html/index.htm
- platformio.ini
- src/rancilio-pid.cpp
When using software brew detection, allow settings max brew counter value without enabling bd pid.
> Show SW brew detection time parameter

- .github/workflows/main.yml
Use hosted GitHub Actions instead of self-hosted ones for added reliability.
> Use hosted GitHub Actions

- src/rancilio-pid.cpp
To fix build issues due to TOF and TEMPSENSOR being undefined, the include of userConfig.h is pulled forward.
This fixes #284 and fixes #278.
> Pull include of userConfig.h forward

- platformio.ini
- src/RancilioServer.h
- src/rancilio-pid.cpp
* Pin library dependencies to current versions so users always get the same ones
* revert WiFi initialization changes from various-fixes branch
* don't create full text answer when saving parameters
> Pin dependency versions, revert WiFi config changes

- src/Displaytemplatestandard.h
- src/rancilio-pid.cpp
Water level was not published via MQTT.
I also re-positioned the water level percentage on the display. It was 1 pixel lower than the MQTT string and touched the MQTT string horizontally. So I moved it up by 1 pixel and to the right by 5 pixel.
Before:
After:
> Add ToF sensor data/water level to MQTT

- src/powerswitchvoid.h
- src/rancilio-pid.cpp
- src/userConfig_sample.h
This feature was tested on my Rancilio Silvia (both trigger and classic switch) and it works with my esp8266.
It currently only supports inputs with integrated or external pull-down resistors.
If you looking forward to merge this feature, I am willing to update the documentation.
> Alpha 3.0.0/Added ability to turn heating on and off with an hardware switch

- platformio.ini
- src/main.cpp
old TSIC lib was only needed on esp8266, so removed
> Remove old TSIC Lib

- data/js/app.js
- src/EmbeddedWebserver.h
- src/Storage.cpp
- src/Storage.h
- src/defaults.h
- src/display.h
- src/main.cpp
- src/standby.h
* Add a new power section in the web interface
* Switch standby mode on or off, set the duration until the heater is turned off 
* Ways to exit the standby mode:
* Brew detection
* Toggle pid controller/steam mode from web interface
* Set pidON/steamON to 1 via MQTT
* Timer counts down from the configured duration and is reset by state transitions to kBrew, kSteam and kBackflush
> Add a configurable standby mode that turns off the heater after a certain amount of time

- src/ISR.cpp
- src/esp32devkitcv4.h
- src/esp8266nodemcuv2.h
- src/hardware.h
- src/rancilio-pid.cpp
- src/userConfig_sample.h
moved pinmapping out of userconfig, pinmapping based on MCU TYPE automatically
for esp8266 board manual changes based on feature set are still necessary, has to be done in "esp8266nodemcuv2.h"
change standard PINBREWSWITCH for esp8266, because PIN A0 mostly causes problems, PIN 15 is the better choise
> pinmapping based on MCU type

- src/EmbeddedWebserver.h
integrity hash was wrong, bs not loaded. removed for local. 
I am in favor of always loading the files locally from ESP32 without online verification.
> Fix because bootstrap JS wasnt loading

- src/EmbeddedWebserver.h
- src/MQTT.h
- src/main.cpp
- src/userConfig_sample.h
* Updated MQTT.h to add core and supporting functions
* Updated userConfig_sample.h to introduce new options:
*  #define MQTT_HASSIO_SUPPORT 0                           // Enables the Homeassistant Auto Discovery Feature
* #define MQTT_HASSIO_DISCOVERY_PREFIX "homeassistant"    // Homeassistant Auto Discovery Prefix
* Implemented a ToDo inside MQTT and also cleaned it a bit
* Established a Task which runs every n Seconds to update Hassio Discovery defined by `const unsigned long HomeAssistantDiscoveryExecutionInterval = 300000;` in main.cpp
> Add Homeassistant Discovery Feature

- src/main.cpp
> fix never entering offline mode

- src/rancilio-pid.cpp
If BREWDETECTION is set to 3 PID only hardware brew detection with an optocoupler the pinMode of PINBREWSWITCH is not set correctly.  In this case the pinMode should be what is set for PINMODEVOLTAGESENSOR. But after setting it to the correct value it is directly overwritten in the next if block.
> Fix pinMode of PINBREWSWITCH for pid only hardware brew detection

- src/main.cpp
I regularly had the issue, that my machine would run in an emergency stop during a coldstart. It appears, that my machine exceeds the default maxChangeRate of 10°C/s of the ZACwire library. This PR  increases the expected maximum temperature change rate before ZACwire library will throw an error (see https://github.com/lebuni/ZACwire-Library#adjustment-for-fast-systems for reference)
> Increase maxChangeRate for TSic 306 sensor

- src/rancilio-pid.cpp
- src/userConfig_sample.h
BREWSWITCHTYPE wasn´t 0 in userconfig_sample
causing problems with optocoppler brewdetection
fix some comments in userconfig_sample
bump hotfix version
> fix standard settings BREWSWITCHTYPE

- src/main.cpp
Not sure why LittleFS usage reporting did not use the existing debugPrintf function. Also, the format string for usage was not correct and not value was logged. 
So, this fix uses debugPrint, fixes the format string, calculates the percentage for the usage and prints one line.
> use debugPrintf instead of Serial.print* and fix format string

- src/rancilio-pid.cpp
- src/userConfig_sample.h
reset reconnect counter MQTT after succesfull connection. see Issue https://github.com/rancilio-pid/clevercoffee/issues/345
Bring SW Numer to 3.3.0 for new release
> Fix for MQTT Reconnect, bumb sw number

- src/Displayrotateupright.h
fix not declared variables as mentioned in issue [#401 ](https://github.com/rancilio-pid/clevercoffee/issues/401)
> Fix for Displayrotateupright.h

- README.md
> README.md:  Included that brew switch can be reconfigured to a push button

- platformio.ini
ESPAsyncWebserver doesn't seem to be actively maintained anymore.
The esphome fork seems to have found a solution for the breaking changes introduced with version 5.1 of the espressif platform.
Updating the display and json libs while we're at it.
> Upgrade espressif platform and some libraries, switch to esphome fork of ESPAsyncWebserver

- src/main.cpp
- src/userConfig_sample.h
Rename VOLTAGESENSORTYPE to OPTOCOUPLERTYPE to be more clear about the used hardware an function.
Also removed PINMODEVOLTAGESENSOR and setting PINMODE based on OPTOCOUPLERTYPE.
I´m seeing this to be a preparation for future implementation of another brew detection with a reed sensor.
> rename voltagesensor to beter represent the hardware 

- platformio.ini
A recent commit of the esphome-fork of the AsyncTCP library that adds IPv6 support (42a8644bb2fe2e0526a35eeaa6021dd55c1b362c) leads to build errors with the latest version of their fork auf ESPAsyncWebserver. 
Pinning the version of AsyncTCP to 2.0.1 for the time being.
> Pin library version of esphome/AsyncTCP

- platformio.ini
- src/main.cpp
- src/userConfig_sample.h
ArduinoOTA is setting mDNS, so OTAHOST was used to set mDNS Record
mDNS is now hostname.local instead otahost.local
using mDNS for OTA Update and monitoring
website is also reachable through hostname.local
TODO: Discuss -> using the same password for OTA and Wifimanager AP    
-> remove posibility to disable ota because mDNS will be turned off aswell
> improve mDNS

- src/steamswitchvoid.h
this got mixed up between optcoupler PR and brew switch + steam switch PR
> fix optocoupler in steam switch

- src/brewvoid.h
- src/defaults.h
- src/display.h
- src/languages.h
- src/main.cpp
- src/userConfig_sample.h
When the water level is low during backflush the pump would keep running because the state machine would go to kWaterEmpty without deactivating backflush mode
> Fix bug in state machine with low water level during backflush

- src/brewvoid.h
- src/display.h
Fix: Backflush for Brewtrigger was immediately restarted when trying to abort.
Water-Empty-Icon shown while Backflush runs and water gets empty.
>  Fix: Backflush not possible to abort for "Brew-Trigger" Switches

- src/embeddedWebserver.h
When enabling nointernet mode, the bootstrap css wasn't loaded because the integrity hash was wrong.
> fix wrong bootstrap digest

- src/mqtt.h
unit_of_measurement="null" was invalid
> fix Home Assist Autodiscovery for sensor/machineState

- src/brewHandler.h
Bugfix for Backflush not stopping when having Brew-switch configured as trigger:
Fixes behaviour for brewtrigger.
Adds one debug message for website-abort and extends debug message for backflush to include the backflush counter.
Bug:
- Configure brew switch as trigger
- Switch on Backflush via Webinterface
- Start Backflush with Brew-Trigger
- Backflush runs & finishes, stops at "press brewswitch to stop", even though mechanical brew trigger is off
Effect:
- When switching off Backflush via Webinterface, Display jumps between "normal Display" and "Backflush Display"
Desired outcome:
- Backflush jumps back to "press brew to start" once backflush-cycle is complete
> Bugfix: Backflush not stopping when Brew-trigger configured

- src/storage.h
always store calibration value, even only one hx711 is used.
otherwise storage gets messy
> always store scalecalibration

- src/display/displayCommon.h
- src/main.cpp
The brew detection got removed recently from the kAtSetpoint state which is 1° below the setpoint but it seems it should also be run there. In this state, the heating logo is already disabled so the shot timer should also work as in kBrew. The display looks the same in both cases so this was a bit confusing.
> make sure the shot timer also shows when still in kAtSetpoint

- src/defaults.h
Values where limited on website, so values from Handbook aren´t usable
> change max PID Value

- src/main.cpp
> Optocoupler: do not use GPIOPin::Type values put Arduino values

- src/brewHandler.h
- src/display/displayCommon.h
- src/display/displayRotateUpright.h
- src/display/displayTemplateMinimal.h
- src/display/displayTemplateScale.h
- src/display/displayTemplateStandard.h
- src/display/displayTemplateUpright.h
- src/embeddedWebserver.h
- src/main.cpp
- src/mqtt.h
- src/scaleHandler.h
- src/userConfig_sample.h
Removed the precompiler makros ONLYPID and ONLYPIDSCALE
ONLYPID got replaced with BREWCONTROL_TYPE 0 -> No pump or valve controll enabled 
ONLYPIDSCALE got replaced with a FEATURE_ makro (FEATURE_SCALE 0 or 1) to follow the naming scheme 
When the scale is activated SHOTTIMER_TYPE 2 and BREWMODE 0 could be used to show the weight, with BREWMODE 2 weight controlls pump and valve action
> Remove ONLYPID and ONLYPIDSCALE

- data/html_fragments/header.html
- data/manifest.json
- src/embeddedWebserver.h
Added manifest file to use the WebApp like a "normal" app when added to the home screen. 
The IP should be set static, otherwise the router may give it a different IP.
Tested with Safari on iPhone 13 Pro with iOS 17.4.
1. Click the "Share" button
2. Click "Add to Homescreen"
3. Click "Add"
4. Now it should be added on your homescreen and be used in standalone mode
> Add WebApp Manifest file

- src/display/displayTemplateScale.h
use mashine state to decide if weight setpoint or current weight should be shown
> fix brewSwitch in ScaleTemplate

- src/display/displayCommon.h
- src/display/displayTemplateMinimal.h
- src/display/displayTemplateScale.h
- src/display/displayTemplateStandard.h
- src/display/displayTemplateTempOnly.h
- src/display/displayTemplateUpright.h
- src/main.cpp
This PR drops the `ColdStart` state. The only difference with respect to `PidNormal` was that it made use of *PonM* in case it was activated. `PidNormal` always ignored this setting.
This PR moves *PonM* to the `PidNormal` state.
The `AtSetPoint` state was only entered from the `ColdStart` state and did not serve any purpose, hence it is also removed.
Without the `ColdStart` state, the condition for displaying the heating logo had to be changed. It is now displayed whenever in the `PidNormal` state *and* when the temperature is at least 5degC below the setpoint.
> Draft: Drop ColdStart and AtSetPoint States

- src/hardware/IOSwitch.cpp
- src/hardware/IOSwitch.h
- src/hardware/Switch.h
- src/main.cpp
This makes a few changes to the switch classes:
* `Switch` now holds its own `Type` and `Mode`
* `IOSwitch` now holds its private `GPIOPin` and also constructs it
This simplifies the overall code, encapsulates GPIO pins where they belong and removes global pointer objects.
> Improve Switch Classes

- src/display/displayCommon.h
- src/display/displayRotateUpright.h
- src/display/displayTemplateMinimal.h
- src/display/displayTemplateScale.h
- src/display/displayTemplateStandard.h
- src/display/displayTemplateTempOnly.h
- src/display/displayTemplateUpright.h
- src/main.cpp
This PR starts simplifying (with a first baby step) the display code. Main problem:
* We first call `displayMachineState()` (unless in rotated display mode)
* Then we call `printscreen()`.
* In order for the latter not to overwrite the previously printed screen, there is an enormous `if` clause which attempts to be the inverse of all `if`s in `displayMachineState()`.
This leads to obvious problems as soon as we change sth somewhere. This PR essentially does one simple thing:
* `displayMachineState` returns a boolean telling us whether it *actually* updated things
* We call this directly from `printscreen()` and only proceed overwriting if it returned `false` (screen not updated)
This gets rid of the enormous and error-prone `if` as well as the use of `#ifdef` for the upright display - we …
> Display: Simplify updating display

- .pre-commit-config.yaml
- src/hardware/Switch.h
- src/main.cpp
- src/utils/Timer.h
This fixes a typo introduced in 51f8c5cdce2bc49a71333ef6827970490769f572
> Hotfix: Fix PID Mode after Startup

- src/hardware/IOSwitch.cpp
- src/hardware/IOSwitch.h
- src/hardware/Switch.h
- src/main.cpp
This is a small improvement to the IOSwitch class which allows setting the initial state.
This fixes an issue when the "water empty" state would briefly flash at startup because the sensor initial state is `LOW`, but we use `HIGH` as the "water is present" state.
> IOSwitch: Allow seeting initial state

- src/brewHandler.h
- src/hardware/TempSensor.h
- src/hardware/TempSensorDallas.cpp
- src/hardware/TempSensorDallas.h
- src/hardware/TempSensorTSIC.cpp
- src/hardware/TempSensorTSIC.h
- src/main.cpp
This PR
* moves error checking into the respective temperature reading classes
* checks for the appropriate error codes provided by the libraries
* moves the temperature sampling / reading into the `TempSensor` class and triggers it with a `Timer`
This means that
* No bogus/wrong temperature values will ever reach the PID, only valid ones are returned. Worst case scenario is errors at startup, then a temperature of 0degC will be returned
* Lots of global `main()` code could be removed and complexity reduced, errors as well as temperature are directly fetched from sensor
* ...and a few other niceties.
> Rework Temperature & Error Handling

- src/display/displayTemplateScale.h
- src/display/displayTemplateStandard.h
- src/display/displayTemplateUpright.h
- src/main.cpp
This MR does two things:
* It drops the `kCooldown` state since that just meant PID off (which is anyway the case because we're off the target value) and seeting a different emergency temperature
* It fixes a single emergency temperature to 145degC instead of swapping between 120 and 145. This is more like the original Silvia hardware where a single thermostat is used for the emergency shutoff (still in use)
> Drop Cooldown State

- src/main.cpp
Add exit condition for steam state. 
As I type this I am no longer sure that this is the correct approach -- do we need special handling for trigger type steam switches, or is the variable `steamOn` filled "intelligently"?
> Exit kSteam mode when steam button is switched off

- data/js/app.js
- src/brewHandler.h
- src/defaults.h
- src/display/displayCommon.h
- src/display/displayRotateUpright.h
- src/display/displayTemplateMinimal.h
- src/display/displayTemplateScale.h
- src/display/displayTemplateStandard.h
- src/display/displayTemplateUpright.h
- src/main.cpp
- src/scaleHandler.h
- src/userConfig_sample.h
brewHandler.h/userConfig_sample.h:
Removed the brew by weight as a separate type and included its functionality in brew by time for easier maintenance.
displayCommon.h:
Updated SHOTTIMER_TYPE 2 (With scale) to functionality already available at SHOTTIMER_TYPE 1
> Fix Shottimer Scale and inclusion of BREWCONTROL_TYPE 2 in 1, with choice of brew-type via parameter in Website

- platformio.ini
there where some changes in release structure -> build checks will download wrong version and build fails
> bumb AsyncTCP and AsyncWebServer Version

- auto_firmware_version.py
Switched from pkg_resources to importlib,
since pkg_resources is deprecated (and I couldn't compile with it).
> Switched from pkg_resources to importlib

- src/main.cpp
if mashine is in kWaterEmpty and water gets refilled, standby time will be resetted
> waterFull will reset standbytime if mashine state is KWaterEmpty

- src/display/displayRotateUpright.h
A fixed rotation U8G2_R1 was hardcoded, but some vertical displays are installed in the opposite way, there U8G2_R3 is required. Use the user config settings to make it universal
> Update vertical template to support displayrotate instead of fixed orientation

- src/main.cpp
when detecting a brew and disabling the PID, the pidOutput needs to be set to 0 and the heater shut off manually
previously the heating continued on its last set intensity for the time set in brewPIDDelay
Screenshot before:
Screenshot after:
> fix pid off on brew detection

- .gitignore
- src/defaults.h
- src/embeddedWebserver.h
- src/main.cpp
- src/mqtt.h
- src/storage.h
The PID controller was still using the P and I values of the old cold start mode which has since been removed. This commit refactors the method that sets the PID tunings so that it takes PonM into account when enabled.
> Fix PonM mode for PID controller

- src/main.cpp
When using scales and MQTT it would bootloop when trying to send the old weightSetpoint. Replaced with targetBrewWeight and it runs well, though there may be more to clean up in this area.
> fixed mqtt crashing caused by old weightSetpoint
